module.exports.ACTION_TYPES = {
  FETCH_TODOS: 'FETCH_TODOS',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
  CREATE_TODO: 'CREATE_TODO',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',
  UPDATE_TODO: 'UPDATE_TODO',
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
  SNOOZE_ALL_SUCCESS: 'SNOOZE_ALL_SUCCESS',
};

module.exports.snoozeOptions = {
  '5m': 'in 5 minutes',
  '15m': 'in 15 minutes',
  '30m': 'in 30 minutes',
  '45m': 'in 45 minutes',
  '1h': 'in 1 hour',
  '2h': 'in 2 hours',
  '3h': 'in 3 hours',
  '4h': 'in 4 hours',
  '8h': 'in 8 hours',
  '12h': 'in 12 hours',
  '20h': 'in 20 hours',
  '1d': 'in 1 day',
  '2d': 'in 2 days',
  '3d': 'in 3 days',
  '1w': 'in 1 week',
  '2w': 'in 2 weeks',
  '1mo': 'in 1 month',
  '3mo': 'in 3 months',
  '6mo': 'in 6 months',
  '1y': 'in 1 year',
  'tonight': '6pm',
  'morrow morn': 'tomorrow at 9am',
  'morrow noon': 'tomorrow at noon',
  'morrow eve': 'tomorrow at 5pm',
  'Su': 'Sunday at noon',
  'M': 'Monday at noon',
  'Tu': 'Tuesday at noon',
  'W': 'Wednesday at noon',
  'Th': 'Thursday at noon',
  'F': 'Friday at noon',
  'Sa': 'Saturday at noon',
};

module.exports.repeatSugar = {
  'hourly': 'in an hour',
  'daily': 'tomorrow at noon',
  'nightly': 'tomorrow at 5pm',
  'weekly': 'Sunday noon',
  'monthly': 'the beginning of next month',
  'sundays': 'Sunday noon',
  'mondays': 'Monday noon',
  'tuesdays': 'Tuesday noon',
  'wednesdays': 'Wednesday noon',
  'thursdays': 'Thursday noon',
  'fridays': 'Friday noon',
  'saturdays': 'Saturday noon',
};
