version: '3'  # version of compose format

services:
  jdo-service:
    build: .  # path is relative to docker-compose.yml localtion
    volumes:
      - .:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container
