version: '3'  # version of compose format

services:
  jdo-service:
    build: .  # path is relative to docker-compose.yml localtion
    volumes:
      - ./app:/app # mount point
      - /Users/jhaddad/jdo/:/var/lib/
    ports:
      - 5005:8000  # host:container
